service: twitter-superadmin

provider:
  name: aws
  runtime: nodejs12.x

  region: ap-south-1
  iamRoleStatements: 
    - Effect: Allow
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:ap-south-1:*:*'

  environment:
    ACTIONS_TABLE: admin_actions
    LOGS_TABLE: logs
    CALLBACKS_TABLE: action_callbacks
    TWEETS_TABLE: tweets

functions:
  logs:
    handler: services/logs.list
    events:
      - http:
         path: /listLogs/{type}
         method: get
         cors: true
  approve:
    handler: services/approve.approveAction
    events:
      - http:
         path: /approveAction
         method: post
         cors: true
  insight:
    handler: services/insights.getData
    events:
      - http:
         path: /getInsights
         method: post
         cors: true