service: twitter-admin

provider:
  name: aws
  runtime: nodejs12.x


  region: ap-south-1
  iamRoleStatements: 
    - Effect: Allow
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:ap-south-1:*:*'

  environment:
    ACTIONS_TABLE: admin_actions
    LOGS_TABLE: logs
    TWEET_ACTIONS: createTweet,updateTweet,deleteTweet

functions:
  users:
    handler: services/user.editUser
    events:
      - http:
         path: /editUser
         method: post
         cors: true
  tweets:
    handler: services/tweet.manageTweets
    events:
      - http:
         path: /tweets
         method: post
         cors: true
